# Generated by Django 5.2.13 on 2026-06-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default='default', max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='dataapp.uploadeddataset')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='dataapp_con_session_f52398_idx'), models.Index(fields=['dataset', 'created_at'], name='dataapp_con_dataset_724860_idx')],
            },
        ),
    ]
